name: blogging-app

services:
  nginx:
    ports:
      - '$CONTAINER_PROD_PORT:80'

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - NODE_ENV=production
    image: blog-app-prod
    environment:
      - NODE_ENV=production
    command: npm run start
    env_file: .env
    # ports:
    #   - '$CONTAINER_PROD_PORT:$PORT'